ibw_job:
    pattern:  /
    defaults: { _controller: "IbwKoperasiBundle:Job:index" }

ibw_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "IbwKoperasiBundle:Job:show" }
    requirements:
        id:  \d+

ibw_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "IbwKoperasiBundle:Job:preview" }
    requirements:
        token:  \w+

ibw_job_new:
    pattern:  /new
    defaults: { _controller: "IbwKoperasiBundle:Job:new" }

ibw_job_create:
    pattern:  /create
    defaults: { _controller: "IbwKoperasiBundle:Job:create" }
    requirements: { _method: post }

ibw_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "IbwKoperasiBundle:Job:edit" }

ibw_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "IbwKoperasiBundle:Job:update" }
    requirements: { _method: post|put }

ibw_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "IbwKoperasiBundle:Job:delete" }
    requirements: { _method: post|delete }

ibw_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "IbwKoperasiBundle:Job:publish" }
    requirements: { _method: post }

